# Generated by Django 3.0.3 on 2020-07-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('father_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField()),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=264)),
                ('id_proof', models.CharField(max_length=264)),
                ('id_proof_no', models.IntegerField()),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=264)),
                ('amount', models.IntegerField()),
                ('due', models.IntegerField()),
                ('rec_no', models.IntegerField()),
                ('rec_date', models.DateField()),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_profile.User_Data')),
            ],
        ),
    ]
