# Generated by Django 3.0.3 on 2020-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='file',
            field=models.FileField(default=1, upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
