# Generated by Django 3.0.3 on 2020-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_profile', '0003_auto_20200714_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='file',
            field=models.ImageField(upload_to='user_image'),
        ),
    ]
