# Generated by Django 3.0.3 on 2020-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_profile', '0004_auto_20200714_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_data',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
