# Generated by Django 3.0.3 on 2020-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_profile', '0005_bill_data_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_data',
            name='due',
        ),
        migrations.AddField(
            model_name='user_data',
            name='due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
