# Generated by Django 3.0.3 on 2020-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_profile', '0006_auto_20200719_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='status',
            field=models.CharField(default=2, max_length=264),
            preserve_default=False,
        ),
    ]
